services:
  monster-sets:
    image: ghcr.io/mktahmasbi99/monstersets:latest
    container_name: monster-sets
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      TZ: ${TZ:-Europe/Warsaw}
      MONSTER_SETS_DB: /data/monster_sets.sqlite3
    volumes:
      - ./data:/data
